# Extra autostart processes
# exec-once = uwsm app -- my-service

exec-once = uwsm app -- copyq --start-server
exec-once = /home/coolbit/.joplin/Joplin.AppImage
# exec-once = hyprctl dispatch workspace 1 && uwsm app -- $TERMINAL --working-directory="$(omarchy-cmd-terminal-cwd)"
# exec-once = hyprctl dispatch workspace 2 && zen &
