windowrule = float, class:com.github.hluk.copyq
windowrule = float, class:Zotero
windowrule = float, class:io.github.alainm23.planify
windowrule = float, class:org.gnome.World.Iotas
windowrule = float, class:pomodorolm
windowrule = float, class:anki
windowrule = float, class:org.gnome.Cheese
# windowrule = workspace:10, class:chrome-instagram.com__-Profile_4
# windowrule = workspace:2, class:zen
# windowrule = workspace:10, class:chrome-web.whatsapp.com__-Profile_4
